### ISSUE TITLE
check for urllib3 first, before using urllib2

### ISSUE THREAD

**Issue by Some1Somewhere** [miso-belica/jusText#49]
I have another package that installs urllib2, and therefore the import below succeeds, and then proceeds to break in Python 3.12 

```py
    import urllib2 as urllib
    URLError = urllib.URLError
 ```
 
 If we can upgrade this to check for urllib3 before trying urllib2, then having urllib2 won't break. 
 
 ```py3tb
|   File "/usr/local/lib/python3.12/site-packages/justext/_compat.py", line 22, in <module>
|     import urllib2 as urllib
|   File "/usr/local/lib/python3.12/site-packages/urllib2.py", line 220
|     raise AttributeError, attr
```

**Comment by miso-belica** [comment]
I am not sure I understand. urllib2 is builtin library so there is no need to install it. And urllib3 is 3rd party package so I don)t want to test it in my code. The code is there only for compatibility between Python v2 and v3. Maybe I am missing some context?

https://github.com/miso-belica/jusText/blob/7fae5d457613cc96cf9ccb070e4aa2e70455f0e2/justext/_compat.py#L21-L26

**Comment by Hebali** [comment]
There seems to be a compatibility issue impacting more recent versions of python:

```
  File "/opt/homebrew/lib/python3.11/site-packages/justext/__init__.py", line 12, in <module>
    from .core import justext
  File "/opt/homebrew/lib/python3.11/site-packages/justext/core.py", line 24, in <module>
    from ._compat import unicode, ignored
  File "/opt/homebrew/lib/python3.11/site-packages/justext/_compat.py", line 22, in <module>
    import urllib2 as urllib
  File "/opt/homebrew/lib/python3.11/site-packages/urllib2.py", line 220
    raise AttributeError, attr
```

**Comment by Hebali** [comment]
@miso-belica if you tested on Python 3.11+?

**Comment by miso-belica** [comment]
Tests in CI are set to run under v3.11 and v3.12 so I expect it should work.

**Comment by Hebali** [comment]
Hmm, something is amiss though. I have the same issue as @Some1Somewhere

**Comment by miso-belica** [comment]
@Hebali can you share the whole CLI command or relevant code about how you trying to use justext?

**Comment by Hebali** [comment]
Just the import statement:
`import justext`

Results in:
```
Traceback (most recent call last):
  File "/Users/heb/Desktop/justext_test.py", line 2, in <module>
    import justext
  File "/opt/homebrew/lib/python3.11/site-packages/justext/__init__.py", line 12, in <module>
    from .core import justext
  File "/opt/homebrew/lib/python3.11/site-packages/justext/core.py", line 24, in <module>
    from ._compat import unicode, ignored
  File "/opt/homebrew/lib/python3.11/site-packages/justext/_compat.py", line 22, in <module>
    import urllib2 as urllib
  File "/opt/homebrew/lib/python3.11/site-packages/urllib2.py", line 220
    raise AttributeError, attr
                        ^
SyntaxError: invalid syntax
```

Running Python 3.11.7

**Comment by miso-belica** [comment]
@Hebali can you run this command on your PC? Maybe it's related to Mac? I am on Windows and it works fine. https://docs.astral.sh/uv/getting-started/installation/

```
uvx --python 3.11.7 --with justext python -c "import justext"
```

**Comment by Hebali** [comment]
On this system, that command returns no output. Hmm

**Comment by miso-belica** [comment]
@Hebali but that is correct right? It just imports justext. So no error. From the stacktrace you provided it seems like you Python env is somehow corrupted because the SyntaxError suggests you are trying to import urllib2 package with Python 2 syntax in Python 3 interpreter. The new syntax is `except Exception as e` instead of `except Exception, e`

**Comment by miso-belica** [comment]
@Hebali but that is correct right? It just imports justext. So no error. From the stacktrace you provided it seems like you Python env is somehow corrupted because the SyntaxError suggests you are trying to import urllib2 package with Python 2 syntax in Python 3 interpreter? Or maybe something else what is not supported in Python 3.

**Comment by Some1Somewhere** [comment]
Yup, the issue is definitely if urllib2 is present, as well as urllib3. My case where urllib2 is installed by another package (https://github.com/raduangelescu/gutenbergpy/issues/24) through httpsproxy_urllib2. If I don't have the httpsproxy_urllib2 package installed, then `import justtext` works fine.

```
pip uninstall httpsproxy-urllib2
Found existing installation: httpsproxy_urllib2 1.0
Uninstalling httpsproxy_urllib2-1.0:
  Would remove:
    /usr/local/lib/python3.12/site-packages/httplib.py
    /usr/local/lib/python3.12/site-packages/httpsproxy_urllib2-1.0.dist-info/*
    /usr/local/lib/python3.12/site-packages/urllib2.py
Proceed (Y/n)? Y
  Successfully uninstalled httpsproxy_urllib2-1.0

$ python
Python 3.12.9 (main, Feb  6 2025, 22:37:05) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import justext
>>> exit()

$ pip install httpsproxy-urllib2
Collecting httpsproxy-urllib2
  Using cached httpsproxy_urllib2-1.0-py3-none-any.whl
Installing collected packages: httpsproxy-urllib2
Successfully installed httpsproxy-urllib2-1.0

$ python         
Python 3.12.9 (main, Feb  6 2025, 22:37:05) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import justext
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.12/site-packages/justext/__init__.py", line 12, in <module>
    from .core import justext
  File "/usr/local/lib/python3.12/site-packages/justext/core.py", line 24, in <module>
    from ._compat import unicode, ignored
  File "/usr/local/lib/python3.12/site-packages/justext/_compat.py", line 22, in <module>
    import urllib2 as urllib
  File "/usr/local/lib/python3.12/site-packages/urllib2.py", line 220
    raise AttributeError, attr
                        ^
SyntaxError: invalid syntax

```

**Comment by miso-belica** [comment]
I have released the version 3.0.2. It should import urllib instead of urllib2 in Python 3 env. Let me know if it solved your problems.

**Comment by Hebali** [comment]
@miso-belica That does the trick, thanks so much!
